import sys
import time
import random
from menu import Menu
from game_engine import Console, Player

console = Console()
player = Player()
start = True
basement_suprise = ["demon", "open", "closed", "bear"]
sus_building = ["enemy_trap", "human_traffic", "smuggler"]
boat_stuff = ["tip over", "fight", "safe"]
truck_survive = ["no", "yes"]
# I know I don't need so many varibles but still I don't care
go_in = " "
choice = " "
name = " "
start_sim = " "
enter = " "
trust = " "
enter_tower_1 = " "
retry_input = " "
jump_1 = " "
wake_up = " "
escape = " "
bye = 0

# Function to exit the game
def quit():
    print("Okay bye")
    exit(0)

# put the intro here
def intro():
    print("You were invited by your friend to test his newest simulator.")
    time.sleep(1)
    print("He wanted to see how you would react on his invention.")
    time.sleep(1)
    print("Because he wanted to see how people would react on fleeing there own country.")
    time.sleep(1)
    print("And to discover how it is to trade a place you are familiar with for something new.")
    time.sleep(1)
    print("Far away from your friends and family.")
    time.sleep(1)
    print("So he created this simulator called escape simulator.")
    time.sleep(1)
    print("He told you the simulation will take place in a land called Narlilia.")
    time.sleep(1)
    print("The country is in constant war with the civilians.")
    time.sleep(1)
    print("The war is getting so out of hand that the civilians are starting to attack you for being befriend with the leader of the resistance.")
    time.sleep(1)
    print("You don't see a other way out anymore than to escape from the country.")
    time.sleep(1)
    print("The country you love and grow up in.")
    time.sleep(1)
    print("Will you manage to escape out of this country or fail horribly.")
    time.sleep(1)
    console.check_answer("Plz press enter to continue.")

    adventure()

def help():
    print(" ")
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Start part 0
# Start adventure
def adventure():
    print("@: Is anybody there???: ")
    console.check_answer("Plz press enter to continue.")
    time.sleep(1)
    print("@: WHAAAAAA!!!!")
    time.sleep(1)
    print("@: Oh sorry. I didn't expect that you where here already.")
    time.sleep(1)
    player.set_name(console.check_answer("So what is our name user?"))
    print("@: Oh hi " + player.get_name(name) + ". It's nice to meet you.")
    time.sleep(1)
    print("@: I'm escape simulator.")
    time.sleep(1)
    print("@: I'm here to teach you how it is to escape the country you currently live in")
    time.sleep(1)
    print("@: So shall we start the simulator?")
    time.sleep(1)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    print(" ")
    print(67 * "-")
    print(" ")
    run()

def run():
    start_sim = console.check_answer("Will you start the sim?: ", ["1", "yes", "y", "2", "no", "n"]).lower()
    if start_sim == ("1") or start_sim == ("yes") or start_sim == ("y"):
        print("Nyaaa")
        Sim_start()
    elif start_sim == ("2") or start_sim == ("no") or start_sim == ("n"):
        print("@: Uhmmm...")
        time.sleep(1)
        print("@: Are you sure?")
        time.sleep(0.5)
        print("1. Yes")
        time.sleep(0.5)
        print("2. No")
        time.sleep(0.5)
        print(67 * "-")
        print(" ")
        run2()

def run2():
    sure = console.check_answer("Are you sure?: ", ["1", "yes", "y", "2", "no", "n"]).lower()
    if sure == ("1") or sure == ("yes") or sure == ("y"):
        print("@: Ohhh bye then")
        time.sleep(1)
        print("You left the simulator alone without going on the adventure.")
        time.sleep(1)
        print("You never know what would have happened")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        print(" ")
        time.sleep(1)
        print("ENDING 1")
        print("Nope not going to do this")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif sure == ("2") or sure == ("no") or sure == ("n"):
        retry()

def retry():
    print(" ")
    print(67 * "-")
    print(" ")
    time.sleep(1)
    print("So do you want to start the simulator?")
    time.sleep(0.5)
    print("1. yes")
    time.sleep(0.5)
    print("2. no")
    time.sleep(0.5)
    retry_input = console.check_answer("start simulator?: ", ["1", "2", "yes", "y", "no", "n"]).lower()
    if retry_input == ("1") or retry_input == ("yes") or retry_input == ("y"):
        print(" ")
        print(67 * "-")
        print(" ")
        Sim_start()
    elif retry_input == ("2") or retry_input == ("no") or retry_input == ("n"):
        print("@: ARE")
        time.sleep(0.5)
        print("@: YOU")
        time.sleep(0.3)
        print("@: KIDDING")
        time.sleep(0.2)
        print("@: ME!!!!!!!")
        time.sleep(3)
        print("Good job you made the program so pissed that it blow it self up.")
        time.sleep(1)
        print("Now you can't enter the simulator anymore.")
        time.sleep(1)
        print("GG player")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING 2")
        print("BYE BYE SIMULATOR")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# End part 0
# Start part 1
def Sim_start():
    print("You hear a dull beep noise.")
    time.sleep(1)
    print("It sounds like your alarm is going of.")
    time.sleep(1)
    print("So what will you do?")
    time.sleep(1)
    print("1. Wake up.")
    time.sleep(1)
    print("2. Go back to sleep.")
    time.sleep(1)
    print("3. Throw your alarm out of the window.")
    time.sleep(1)
    wake_up = console.check_answer("while you go back to sleep or wake up: ", ["1", "wake up", "2" , "sleep", "3", "throw"]).lower()
    if wake_up == "1" or wake_up == "wake up":
        print(67 * "-")
        print(" ")
        print("You wake up and turn of your alarm.")
        time.sleep(1)
        print("You look at the time and you see that its 10.00 am.")
        time.sleep(1)
        print("You get up out of bed and get yourself ready.")
        time.sleep(1)
        print("Outside you hear the occasional screaming of people and gunshots being fired in the far distance.")
        time.sleep(1)
        print("You are kind of getting sick of this.")
        time.sleep(1)
        print("You go down stairs to get some breakfast.")
        time.sleep(1)
        print("When you got down stairs you see some shady people sitting in your living room.")
        time.sleep(1)
        shady_people()
    elif wake_up == "2" or wake_up == "sleep":
        print(67 * "-")
        print(" ")
        print("zzzzzz")
        time.sleep(1)
        print("zzzzzzzzzzzzzzz......")
        time.sleep(1)
        print("You hear suddenly a loud scream.")
        time.sleep(1)
        print("???: He you lazy peace of shit wake the fuck up!!!!")
        time.sleep(1)
        print("That immediately wakes you up.")
        time.sleep(1)
        print("You look around and then you see your best friend standing by your bed trying to wake up.")
        time.sleep(1)
        print("Her name is Monika and she is the leader of the local resistance group.")
        time.sleep(1)
        print("Monika: Ah you finnally awake.")
        time.sleep(1)
        print("Monika: That took you long enough.")
        time.sleep(1)
        print("You ask what is going on and why she woke you up.")
        time.sleep(1)
        print("Monika: There is no time to explain.")
        time.sleep(1)
        print("Monika: We need to get out of here right the fuck now.")
        time.sleep(1)
        print("You do what Monika tells you.")
        time.sleep(1)
        print("You quickly put on some clothes and leave your house through the back door.")
        time.sleep(1)
        quick_escape()
    elif wake_up == "3" or wake_up == "throw":
        print(67 * "-")
        print(" ")
        print("You grab your alarm and throw it out of the window.")
        time.sleep(1)
        print("The alarm hits the head of a unexpect civilian.")
        time.sleep(1)
        print("People though it was a bomb you throw out so they throw a grenade back to you.")
        time.sleep(1)
        print("*booooooooommmmmm*")
        time.sleep(1)
        print("You got hit by the explosion and died instantly.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING 3")
        print("Unexpected event")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    
def shady_people():
    print("You look again and see its your best friend Monika and some friends of her.")
    time.sleep(1)
    print("Monika is the leader of the resitance in your neighborhood.")
    time.sleep(1)
    print("You start asking what they are doing here.")
    time.sleep(1)
    print("Monika: We are here to warn you that there are some people after you.")
    time.sleep(1)
    print("Monika: And its is the best that you get out of here.")
    time.sleep(1)
    print("Monika: The country is not safe anymore for you.")
    time.sleep(1)
    print("Monika: The found out that you're befriend with me.")
    time.sleep(1)
    print("You ask her what you need to do and if your family is safe.")
    time.sleep(1)
    print("Monika: We have prepared for you a escape route you can take to get out of here.")
    time.sleep(1)
    print("Monika: And don't worry about your family they are safe.")
    time.sleep(1)
    print("Monika: I know some people that can help you leave the country.")
    time.sleep(1)
    print("Monika's phone goes of.")
    time.sleep(1)
    print("Monika picks up the phone and start talking to the person on the phone.")
    time.sleep(1)
    print("After a few minutes of Monika being on the phone.")
    time.sleep(1)
    print("Monika look at you and signs that you need to leave")
    time.sleep(1)
    print("You know something bad is going to happen.")
    time.sleep(1)
    print("How will you leave or will you hide?")
    time.sleep(1)
    print("1. Front door.")
    time.sleep(1)
    print("2. Back door.")
    time.sleep(1)
    print("3. Hide in the basement")
    time.sleep(1)
    escape = console.check_answer("what do you do?: ", ["1", "2", "3", "front", "back", "hide"]).lower()
    if escape == "1" or escape == "front":
        print(67 * "-")
        print(" ")
        print("You quickly make your way towards the front door.")
        time.sleep(1)
        print("You look through the window see if its safe to run.")
        time.sleep(1)
        print("On that moment some throws a smoke grenade on the street.")
        time.sleep(1)
        print("This is my change to escape.")
        time.sleep(1)
        print("You quickly run outside and run a few streets over.")
        time.sleep(1)
        print("You see a man stand there with a van.")
        time.sleep(1)
        print("He seems to recognize you.")
        time.sleep(1)
        print("Van man: Hey " + player.get_name(name) + ". How is it going?")
        time.sleep(1)
        print("When you get closer to him you start to recognize him.")
        time.sleep(1)
        print("Its a your good pall Pablo.")
        time.sleep(1)
        print("You tell him what is going on.")
        time.sleep(1)
        print("Pablo: Awhhhh thats bad man.")
        time.sleep(1)
        print("Pablo: But I think I can help you.")
        time.sleep(1)
        print("Pablo: I know a few friends that do this for business.")
        time.sleep(1)
        print("Pablo: I can bring you in contact with them.")
        time.sleep(1)
        pablo_escape()
    elif escape == "2" or escape == "back":
        print(67 * "-")
        print(" ")
        print("You go through the back door.")
        time.sleep(1)
        print("You see some friends from Monika waiting there for you at a van.")
        time.sleep(1)
        print("A guy walks up to you.")
        time.sleep(1)
        print("A guy: Hey, I heard you needed help getting out of the country, right?")
        time.sleep(1)
        print("You tell him that you indeed do and that you need to leave right now.")
        time.sleep(1)
        print("The guy node's and walks up to the van.")
        time.sleep(1)
        print("A guy: Here look everything we need to cross the borders all arranged by my boss.")
        time.sleep(1)
        print("You look in the van and see fake passports and some other stuff.")
        time.sleep(1)
        monika_escape()
    elif escape == "3" or escape == "hide":
        print(67 * "-")
        print(" ")
        print("You quickly make your way to your basement door.")
        time.sleep(1)
        print("You open you basement door and go down into your basement.")
        time.sleep(1)
        print("You pick up a heavy piece of wood you found on the ground and try to block the door with it.")
        time.sleep(1)
        print("You wait a while in the basement.")
        time.sleep(1)
        basement()

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# RNG route
def basement():
    choice = random.choice(basement_suprise)
    if choice == "bear":
        print("You feel like someone is breathing in your neck.")
        time.sleep(1)
        print("You slowly turn around in the dark basement to check what it is.")
        time.sleep(1)
        print("You put your hands forward to feel what it is.")
        time.sleep(1)
        print("It feels really fluffy and fur like.")
        time.sleep(1)
        print("Wait a second you think to yourself.")
        time.sleep(1)
        print("It would have impossible that that bear you locked up here a few days weeks ago is still right.")
        time.sleep(1)
        print("Will your are thinking about it the bear is getting ready to murder you")
        time.sleep(1)
        print("*slash* And there you go.")
        time.sleep(1)
        print("Killed by a bear.")
        time.sleep(1)
        print("R.I.P. " + player.get_name(name) + ".")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING BEAR")
        print("schrödinger bear")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "demon":
        print("You are alone down in the basement.")
        time.sleep(1)
        print("You suddenly hear a voice coming from the dark corner of the room.")
        time.sleep(1)
        print("Co...me.... wi....th.. u...s....")
        time.sleep(1)
        print("You were pretty sure that there is nothing else down here..... RIGHT????")
        time.sleep(1)
        print("You feel chill flowing down your spine.")
        time.sleep(1)
        print("You know there is something down here. There has to be right......")
        time.sleep(1)
        print("You starting to panic and don't know what to do.")
        time.sleep(1)
        print("The panic is so overwhelming that you feel like that you don't want to be here anymore.")
        time.sleep(1)
        print("You lose consciousness.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING 666")
        print("Demonic take over")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "open":
        print("After hiding in the basement for a while you hear some people entering your house.")
        time.sleep(1)
        print("Angery man: Hey " + player.get_name(name) + "we know your in here.")
        time.sleep(1)
        print("You hear them going through your house.")
        time.sleep(1)
        print("You hope the are unable to find you.")
        time.sleep(1)
        print("You suddenly hear them kicking against the basement door")
        time.sleep(1)
        print("You hope the door can hold it.")
        time.sleep(1)
        print("Then you hear *bam* the door flies downwards right in your face.")
        time.sleep(1)
        print("The door knocks you unconscious.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING DOOR")
        print("Knock knock who is there?")
        time.sleep(1)
        print("The door")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "closed":
        print("After hiding in the basement for a while you hear some people entering your house.")
        time.sleep(1)
        print("Angery man: Hey " + player.get_name(name) + "we know your in here.")
        time.sleep(1)
        print("You hear them going through your house.")
        time.sleep(1)
        print("You hope the are unable to find you.")
        time.sleep(1)
        print("You suddenly hear them kicking against the basement door")
        time.sleep(1)
        print("You hope the door can hold it.")
        time.sleep(1)
        print("You hear this guy trying really hard to open up the door but the door won't budge.")
        time.sleep(1)
        print("Then you hear someone yell.")
        time.sleep(1)
        print("Angery man: Guys he is nowhere to be found lets move out.")
        time.sleep(1)
        print("You hear everyone that is upstairs leave.")
        time.sleep(1)
        print("You survived this stressfull ordeal.")
        time.sleep(1)
        escaped_basement()

def escaped_basement():
    print("You slowly make your way to the basement door.")
    time.sleep(1)
    print("You put your ear up to the door to be sure that everyone left.")
    time.sleep(1)
    print("You don't hear anything.")
    time.sleep(1)
    print("You slowly open the door and hope that there is no one left.")
    time.sleep(1)
    print("When you look around you don't see a single person in the building left.")
    time.sleep(1)
    print("You go through the back door and run a trough a couple of streets.")
    time.sleep(1)
    print("You see there a sign above a build saying 'way out of the country'.")
    time.sleep(1)
    print("It look really shady but you think to yourself what other choose do I have left.")
    time.sleep(1)
    print("Do you go in or search for a other way out?")
    time.sleep(1)
    print("1. Go in.")
    time.sleep(1)
    print("2. Search for a other way.")
    time.sleep(1)
    go_in = console.check_answer("What do you do?", ["1", "2", "go in", "search"]).lower()
    if go_in == "1" or go_in == "go in":
        print(67 * "-")
        print(" ")
        print("You go into the suspicious building.")
        time.sleep(1)
        suspicious_building()
    elif go_in == "2" or go_in == "search":
        print(67 * "-")
        print(" ")
        print("You decide not to go into the building.")
        time.sleep(1)
        print("You continue your run till you come across a familiar face.")
        time.sleep(1)
        print("Nick: Howdy man.")
        time.sleep(1)
        print("Its your friend Nick")
        time.sleep(1)
        print("Nick is a master in getting people out of the country maybe he can help.")
        time.sleep(1)
        print("So you ask Nick if he can get you out of this country because some bad people are looking for you.")
        time.sleep(1)
        print("Nick: Yeah ofcourse, man.")
        time.sleep(1)
        print("Nick: I can get you out right now if you want.")
        time.sleep(1)
        print("Nick: You know its free because your my best pal.")
        time.sleep(1)
        print("Nick hands you some stuff and then walks to his car.")
        time.sleep(1)
        print("Nick: He come man lets go.")
        time.sleep(1)
        print("You go into Nick's car.")
        time.sleep(1)
        print("You think to yourself what do I have to lose.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        console.check_answer("Plz press enter to continue.")
        print(" ")
        escape_nick()

def suspicious_building():
    choice = random.choice(sus_building)
    if choice == "enemy_trap":
        print("You just walk into the trap of the poeple that are looking for you.")
        time.sleep(1)
        print("They take you hostage.")
        time.sleep(1)
        print("They want to know where Monika is.")
        time.sleep(1)
        print("Obviously you don't know where she is.")
        time.sleep(1)
        print("Now your stuck here with the people that want you as hostage and then dead.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING TRAP")
        print("Its a trap")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
    elif choice == "human_traffic":
        print("You see a man sitting behind a table.")
        time.sleep(1)
        print("Man: Hello stranger, are you here for help to get out of the country?")
        time.sleep(1)
        print("You find the man pretty suspicious but you feel like you have no other choose.")
        time.sleep(1)
        print("You say to him that you indeed need to get out of the country.")
        time.sleep(1)
        print("Man: Ah okay. I will help you get out of here.")
        time.sleep(1)
        print("The man gives you a form.")
        time.sleep(1)
        print("You read trough the form.")
        time.sleep(1)
        print("In the form stands that you will sell them your property and give them a amount of money.")
        time.sleep(1)
        print("You feel like this is wrong")
        time.sleep(1)
        print("But it feels like you have no other option.")
        time.sleep(1)
        print("So you sign the form and give it back to the man.")
        time.sleep(1)
        print("The man smile's and gives you a piece of paper")
        time.sleep(1)
        print("Man: Be on time.")
        time.sleep(1)
        print("On the paper stands a location and time.")
        time.sleep(1)
        escape_traffic()
    elif choice == "smuggler":
        print("You enter a huge warehouse.")
        time.sleep(1)
        print("Man: Ah welcome welcome.")
        time.sleep(1)
        print("You get greeted by a strange man.")
        time.sleep(1)
        print("Man: So you are here to get out of the country yeah right.")
        time.sleep(1)
        print("You tell him that you indeed need to get out of the country.")
        time.sleep(1)
        print("Man: Ofcourse ofcourse.")
        time.sleep(1)
        print("Man: I have a wonderfull way yeah.")
        time.sleep(1)
        print("You ask him how he will get you out.")
        time.sleep(1)
        print("Man: I will put you hidden in this trucks.")
        time.sleep(1)
        print("The man points to the trucks in the warehouse.")
        time.sleep(1)
        print("This feels like a stupid idea.")
        time.sleep(1)
        print("But it feels like you don't have an other choose.")
        time.sleep(1)
        escape_truck()

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# quick escape route
def quick_escape():
    print("When going through the backdoor you see a wierd guy standing there in all black.")
    time.sleep(1)
    print("Man in black: Did you ever had a dream" + player.get_name(name) + "that you seemed so sure it was real?")
    time.sleep(1)
    print("You think what the hell is this man talking about and why does he know my name.")
    time.sleep(1)
    print("You ask him what the hell he is talking about.")
    time.sleep(1)
    print("Man in black: Oh you don't know who I am" + player.get_name(name) + ".")
    time.sleep(1)
    print("Man in black: Its me simon.")
    time.sleep(1)
    print("Simon: The person that let you play this simulator.")
    time.sleep(1)
    print("Simon: It looks like you got stuck in the simulator and I can't get you out again.")
    time.sleep(1)
    print("You get what he is saying.")
    time.sleep(1)
    print("You indeed entered the simulator in his place.")
    time.sleep(1)
    print("You try to exucte the quit command but the sytem give a error.")
    time.sleep(1)
    print("Simon: See the system won't let you out anymore.")
    time.sleep(1)
    print("Simon: You have to follow me to be able to escape the simulator.")
    time.sleep(1)
    print("You suddenly get a message from the system.")
    time.sleep(1)
    print("@: Don't trust him he is a glitch.")
    time.sleep(1)
    print("Simon: Come with me.")
    time.sleep(1)
    print("What will you do.")
    time.sleep(1)
    print("1. Go with Simon")
    time.sleep(1)
    print("2. Trust system")
    time.sleep(1)
    trust = console.check_answer("Simon: Do you trust me?").lower()
    if trust == "1" or trust == "yes":
        print(67 * "-")
        print(" ")
        print("You trust Simon.")
        time.sleep(1)
        print("You follow Simon trough the streets.")
        time.sleep(1)
        print("You end up at a really tall building.")
        time.sleep(1)
        print("Simon: Lets go in.")
        time.sleep(1)
        print("@: Don't go in.")
        time.sleep(1)
        print("@: Plz I can't help you if you go.")
        time.sleep(1)
        enter_tower()
    elif trust == "2" or trust == "no":
        print(67 * "-")
        print(" ")
        print("You trust the sytem.")
        time.sleep(1)
        print("@: Run away from him.")
        time.sleep(1)
        print("@: He is dangerous.")
        time.sleep(1)
        print("@: Follow my signs.")
        time.sleep(1)
        print("Will running you see Simon chasing you.")
        time.sleep(1)
        print("Simon is slowly changing in a wierd like demon creature.")
        time.sleep(1)
        print("Simon: Please come back.")
        time.sleep(1)
        print("Simon: The system is trying to trap you.")
        time.sleep(1)
        print("You keep following the systems arrows till you get at a cliff.")
        time.sleep(1)
        jump()

def enter_tower():
    print("Do you want to enter the tower?")
    time.sleep(1)
    print("1. Ent3r tower")
    time.sleep(1)
    print("2. Enter tow3r")
    time.sleep(1)
    print("3. Enter t0wer")
    time.sleep(1)
    print("4. Don't 3nter t0wer")
    time.sleep(1)
    print("%, En13r 10w3r")
    time.sleep(1)
    enter_tower_1 = console.check_answer("DO YOU ENTER THE TOWER?", ["1", "2", "3", "4", "%", "5", "enter"]).lower()
    if enter_tower_1 == "1" or enter_tower_1 == "2" or enter_tower_1 == "3" or enter_tower_1 == "5" or enter_tower_1 == "enter":
        print(67 * "-")
        print(" ")
        print("You walk into the tower")
        time.sleep(1)
        print("Upon touching the door of the tower you feel like something is trying to corrupt you.")
        time.sleep(1)
        print("S!M0N: Whahahaha, it looks like my plan worked.")
        time.sleep(1)
        print("You ask S!M0N what the hell is going on here.")
        time.sleep(1)
        print("While you ask this you feel immense amount of pain flowing trough you.")
        time.sleep(1)
        print("@: Nooooooo, you walked right into the glitch trap.")
        time.sleep(1)
        print("S!M0N: Shut up system this user is mine now.")
        time.sleep(1)
        print("Suddenly you feel a rush of information going trough you.")
        time.sleep(1)
        print("After that you feel like your conscious is slowly fading away.")
        time.sleep(1)
        print("FATAL ERROR")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 4")
        print("Fatal take over")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif enter_tower_1 == "4":
        print(67 * "-")
        print(" ")
        print("You decide to listen to the system.")
        time.sleep(1)
        print("You turn around and make a run for it.")
        time.sleep(1)
        print("You feel like Simon has been taken over by something very evil.")
        time.sleep(1)
        print("@: Follow my signs")
        time.sleep(1)
        print("You follow systems signs.")
        time.sleep(1)
        print("Until you end up at the end of the cliff.")
        time.sleep(1)
        jump()

def jump():
    print("@: Please jump down.")
    time.sleep(1)
    print("@: Trust me" + player.get_name(name) + ".")
    time.sleep(1)
    print("Do you jump?")
    time.sleep(1)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    jump_1 = console.check_answer("Will you jump?", ["1", "2", "yes", "no", "y", "n"]).lower()
    if jump_1 == "1" or jump_1 == "yes" or jump_1 == "y":
        print(67 * "-")
        print(" ")
        print("You jump down off the cliff.")
        time.sleep(1)
        print("Will falling you feel lik everthing around you is disappearing.")
        time.sleep(1)
        print("Until you see a bright light.")
        time.sleep(1)
        print("Suddenly you wake up in the real world.")
        time.sleep(1)
        print("You ask escape simulator what was going on.")
        time.sleep(1)
        print("@: Oh sorry that was glitched AI.")
        time.sleep(1)
        print("@: He was someone Simon put into the game to let him learn from human actions.")
        time.sleep(1)
        print("@: But what happened in stead was that AI longed to be human.")
        time.sleep(1)
        print("@: So he waited for a unexpected user that he could manipulate.")
        time.sleep(1)
        print("@: So when he saw you he tought he could take his opportunity to strike.")
        time.sleep(1)
        print("@: But as you can see he failed.")
        time.sleep(1)
        print("@: So congratz user you succeeded at escaping.")
        time.sleep(1)
        print("@: This is the end.")
        time.sleep(1)
        print("@: I know this wasn't the end you were hoping for but still.")
        time.sleep(1)
        print("@: I will now wish you farewell user and good luck with everything in live.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("CONGRATZ ON ESCAPING THE PROGRAM!")
        time.sleep(1)
        print(" ")
        print("Ending 6")
        print("Getting out of here")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif jump_1 == "2" or jump_1 == "no" or jump_1 == "n":
        print(67 * "-")
        print(" ")
        print("You decide not to jump.")
        time.sleep(1)
        print("Simon jumps on you and devours you.")
        time.sleep(1)
        print("FATAL ERROR")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 5")
        print("Didn't jump")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()

#------------------------------------------------------------------------------------------------------------------------------------------------------------------
# part 2 escape out of the country
def pablo_escape():
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    print("Pablo takes out his phone and starts a phone call.")
    time.sleep(1)
    print("After a while Pablo comes back to you")
    time.sleep(1)
    print("Pablo: The are coming this way.")
    time.sleep(1)
    print("So you wait there with Pablo for his friends.")
    time.sleep(1)
    print("Then Pablo's friends arive.")
    time.sleep(1)
    print("Man 1: So who is the person that we need to help.")
    time.sleep(1)
    print("Pablo: My friend is here.")
    time.sleep(1)
    print("Then Pablo points at you.")
    time.sleep(1)
    print("Man 1: Okay come with us.")
    time.sleep(1)
    print("You start to follow the Man.")
    time.sleep(1)
    print("You then get to a car.")
    time.sleep(1)
    print("When you are at the car the man put a bag suddenly over your head.")
    time.sleep(1)
    print("You want to scream but you suddenly get knocked out.")
    time.sleep(1)
    print("After a while you wake up.")
    time.sleep(1)
    print("You are stuck in a cage")
    time.sleep(1)
    print("When you look around you you see more people that are stuck in cage's.")
    time.sleep(1)
    print("You feel like you fall in a trap.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    print("SLAVE OR WORSE")
    time.sleep(1)
    print(" ")
    print("ENDING 8")
    print("Became a slave or something.")
    time.sleep(1)
    console.check_answer("Plz press enter to continue.")
    play_again()

def escape_traffic():
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    print("You go to the specified location on the paper.")
    time.sleep(1)
    print("When you arive there you a bunch of people getting loaded on a small boat.")
    time.sleep(1)
    print("You walk up to the man and ask if you are at the right spot.")
    time.sleep(1)
    print("The man say you're and that you need to get a board of the boat.")
    time.sleep(1)
    print("You do what the tell you and get onto the boat.")
    time.sleep(1)
    print("Once everyone was a board of the boat you guys took of.")
    time.sleep(1)
    print("This boat will hopefully take you guys over the ocean out of the country.")
    time.sleep(1)
    print("The trip is taking a while now.")
    time.sleep(1)
    print("You guys are now drifting on the occean slowly trying to go to your destination.")
    time.sleep(1)
    print("Everyone on the boat looks terrified and hope they can make it on shore.")
    time.sleep(1)
    print("You even hear a baby cry on boat.")
    time.sleep(1)
    print("You really hope al of you can make it safely on shore.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    boat_trip()

def boat_trip():
    choice = random.choice(boat_stuff)
    if choice == "tip over":
        print("After a while its starts to storm.")
        time.sleep(1)
        print("The ocean is getting pretty wild and you feel the boat is going to tip over.")
        time.sleep(1)
        print("And then it happens a huge wave hits the boat.")
        time.sleep(1)
        print("Everybody starts to scream for there live.")
        time.sleep(1)
        print("The boat tips over.")
        time.sleep(1)
        print("After that you get pushed down by the waves.")
        time.sleep(1)
        print("You try to swim up but its futile.")
        time.sleep(1)
        print("YOU DIED")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 6")
        print("The drowned")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "fight":
        print("There suddenly breaks out a fight on the boat.")
        time.sleep(1)
        print("People are pissed at each other.")
        time.sleep(1)
        print("Because of the fighting people are starting to fall of.")
        time.sleep(1)
        print("And then suddenly you get a person shoved in your face.")
        time.sleep(1)
        print("You loss your balance and fall of the boat.")
        time.sleep(1)
        print("You start to drift in the ice cold water.")
        time.sleep(1)
        print("After a while you lose concussions.")
        time.sleep(1)
        print("YOU DIED")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 7")
        print("Pushed in sea.")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "safe":
        print("After a while you start to see land.")
        time.sleep(1)
        print("Everybody is happy but still really scared.")
        time.sleep(1)
        print("Eventually you guys hit land.")
        time.sleep(1)
        print("At land are some people that see you get at shore and want to help you.")
        time.sleep(1)
        print("After that you guys get brought to a camp.")
        time.sleep(1)
        print("At the camp you find out this is a refugee camp.")
        time.sleep(1)
        refugee_camp()

def monika_escape():
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    print("A guy: Get in the van so that we can leave.")
    time.sleep(1)
    print("You do as you were told and enter the van.")
    time.sleep(1)
    print("Will being in the van you're told to be silence during the trip.")
    time.sleep(1)
    print("Then you hear the enigne of the van starting.")
    time.sleep(1)
    print("So the trip started.")
    time.sleep(1)
    print("You are there in the truck with a few other people.")
    time.sleep(1)
    print("You are going on a long trip trough country's to try to get to a safe country.")
    time.sleep(1)
    print("Its was a long trip.")
    time.sleep(1)
    print("By sitting hours on end with almost no breaks and almost no food.")
    time.sleep(1)
    print("The van made a couple of stops but we may not come out of the van")
    time.sleep(1)
    print("Sometimes the people of the customs would look into our truck and check our pasports.")
    time.sleep(1)
    print("After checking them the let us go.")
    time.sleep(1)
    print("After a while we finnaly stopped and the doors openend.")
    time.sleep(1)
    print("A guy: You may come out now.")
    time.sleep(1)
    print("A guy: Please follow me.")
    time.sleep(1)
    print("You follow the guy into a building that is tottally boarded of.")
    time.sleep(1)
    print("A guy: We will stay here for the night.")
    time.sleep(1)
    print("A guy: You guys may not go outside.")
    time.sleep(1)
    print("After he sayed that he went outside to smoke.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    the_building()

def the_building():
    print("After the guy left you started to look around.")
    time.sleep(1)
    print("You see that there are two other guys also sitting in this building with you.")
    time.sleep(1)
    print("You try to start with them a conversation with them.")
    time.sleep(1)
    print("They say something along the lines of I'm tired please go to bed.")
    time.sleep(1)
    print("You don't have a good feeling about this place.")
    time.sleep(1)
    print("But you feel way to exhausted to do anything right now.")
    time.sleep(1)
    print("So you decide to sleep here tonight.")
    time.sleep(1)
    print("The next morning you got woken up by the guy that brought you here.")
    time.sleep(1)
    print("A guy: Lets go back to the van its going to be a long trip.")
    time.sleep(1)
    print("So you guys decide to go back into that afwull van.")
    time.sleep(1)
    print("You are again hours on end with no breaks in the van.")
    time.sleep(1)
    print("Till the van stops.")
    time.sleep(1)
    print("The doors opened.")
    time.sleep(1)
    print("A guy: You may come out now.")
    time.sleep(1)
    print("You are in a luscious city.")
    time.sleep(1)
    print("After exiting the van the guy say that he needs to do something so you guys need to wait here.")
    time.sleep(1)
    print("You're super exhausted and don't feel like you want to travel anymore in that van.")
    time.sleep(1)
    print("You see some people walking by and want to ask them where you are in your best english.")
    time.sleep(1)
    print("They tell you that you're in the city Amsteria.")
    time.sleep(1)
    print("Amsteria is the main capital of the country Neatria.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    shelter_Neatria()

def escape_truck():
    print("You start to follow the instructions of the man and you went into the hidden compartment.")
    time.sleep(1)
    print("The hidden compartment is not so big.")
    time.sleep(1)
    print("But it feels like you have no other choose.")
    time.sleep(1)
    print("So you wait in this compartment.")
    time.sleep(1)
    print("Then start the truck and starts your journey.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    truck_trip()

def truck_trip():
    choice = random.choice(truck_survive)
    if choice == "no":
        print("The trip goes on for a while.")
        time.sleep(1)
        print("After a while you feel like you're getting sleepy.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 9")
        print("No oxygen")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "yes":
        print("The trip continue's for a while.")
        time.sleep(1)
        print("You just relax in the truck and wait till you arive at your destination.")
        time.sleep(1)
        print("After a while the truck stop.")
        time.sleep(1)
        print("The compartment door goes open.")
        time.sleep(1)
        print("The truck driver stands there.")
        time.sleep(1)
        print("Driver: We have arrived.")
        time.sleep(1)
        print("You get slowly out of the compartment.")
        time.sleep(1)
        print("While going out you see that the sun is burning in your eyes.")
        time.sleep(1)
        print("You start to put your elbow in front of your face.")
        time.sleep(1)
        print("Then when trying to get out this way you loose your balance.")
        time.sleep(1)
        print("Driver: He calm there budy.")
        time.sleep(1)
        print("The driver catches and helps you to regain your balance.")
        time.sleep(1)
        print("You ask the driver where you are.")
        time.sleep(1)
        print("Driver: We are in the wonderfull country of Jupinia.")
        time.sleep(1)
        print("You think by yourself were that is.")
        time.sleep(1)
        print("Driver: It lays pretty far away from Narlilia.")
        time.sleep(1)
        print("Driver: So don't worry they won't get you here.")
        time.sleep(1)
        print("You're pretty happy to hear those words from the driver.")
        time.sleep(1)
        print("You ask where you can go for to register your self as refugee.")
        time.sleep(1)
        print("Driver: Ah okay I will bring you in contact with my friends.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        console.check_answer("Plz press enter to continue.")
        print(" ")
        jupinia_shelter()

def escape_nick():
    print("Nick start to drive trough the country with no worries that his car would get hit.")
    time.sleep(1)
    print("Will bombs are going of around us Nick is loudly singing with the song on the radio.")
    time.sleep(1)
    print("This goes on for awhile.")
    time.sleep(1)
    print("Till suddenly the car breaks down.")
    time.sleep(1)
    print("Nick: Ah fuck.")
    time.sleep(1)
    print("Nick: That was my favourite car.")
    time.sleep(1)
    print("You ask Nick where you guys are.")
    time.sleep(1)
    print("Nick: We are now in Kolit the neighboring country of Narlilia.")
    time.sleep(1)
    print("You ask if Nick know someone that you can go to and if its safe here.")
    time.sleep(1)
    print("Nick: I know a few friends that can help you.")
    time.sleep(1)
    print("Nick start to call them.")
    time.sleep(1)
    print("After Nick is done with the phone call he says that his friend will pick us up.")
    time.sleep(1)
    print("And that they can get me a job in this country and a place to live.")
    time.sleep(1)
    print("You wait there with Nick for a while.")
    time.sleep(1)
    print("Then a car comes driving towards you guys.")
    time.sleep(1)
    print("The car stops near Nicks broken down car.")
    time.sleep(1)
    print("Men from car: Hey Nick how is it going.")
    time.sleep(1)
    print("Nick: Not so well.")
    time.sleep(1)
    print("Nick: My car broke down will I was helping my pal " + player.get_name(name) + " .")
    time.sleep(1)
    print("Men from car: Yeah boss already told me that.")
    time.sleep(1)
    print("Men from car: So get in and we will get them a nice temporary place and job.")
    time.sleep(1)
    print("You get into the car of the men.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    shelter_kolit()

#-------------------------------------------------------------------------------------------------------------------------------------------------------------
# part 3 New country
def shelter_kolit():
    print("They ride the car to the main capital of Kolit called Meniria.")
    time.sleep(1)
    print("Meniria is a rich city which is also seen by most as the city of freedom.")
    time.sleep(1)
    print("The street of Meniria are mainly ruled by the mafia.")
    time.sleep(1)
    print("The mafia is peacefully ruling this city.")
    time.sleep(1)
    print("The mafia wants to give everyone freedom and a place to live if you want to work for it.")
    time.sleep(1)
    print("This is what the guys in the car told you.")
    time.sleep(1)
    print("And the guy they call boss is the leader of the mafia leading the city.")
    time.sleep(1)
    print("Why the mafia took over was because Meniria was first know as the drug capital and the leader of the mafia hated that.")
    time.sleep(1)
    print("He wants to see a world without drugs.")
    time.sleep(1)
    print("And because the goverment didn't want to do anything against it so the mafia took over.")
    time.sleep(1)
    print("The car just entered the city as they finished the story.")
    time.sleep(1)
    print("While you look around in the city it looks so much different than your own place while the country's are not that far apart.")
    time.sleep(1)
    print("The city looks way more advanced than your own city you lived in.")
    time.sleep(1)
    print("After a while you guys arrive at a small house in the city.")
    time.sleep(1)
    print("Men from car: This is where you while temporarily stay till you have shown us that you are a hard worker.")
    time.sleep(1)
    print("Men from car: I will get the papper works ready for you so don't worry.")
    time.sleep(1)
    print("Men from car: Try to relax now.")
    time.sleep(1)
    print("Men from car: Because I think you had a pretty stressfull day.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    kolit_epilogue()

def shelter_Neatria():
    print("After founding out where you were you started to find someone that could help you guys.")
    time.sleep(1)
    print("Then you saw there a guy that looked like a cop.")
    time.sleep(1)
    print("You asked him if he know someone that could help us.")
    time.sleep(1)
    print("He told us there was a place we could go to find temporarily safe gaurd.")
    time.sleep(1)
    print("He also gave you guys a card in with which you could travel for one day trough the entire country.")
    time.sleep(1)
    print("You thanked him and went on your way to place the cop person had mentioned.")
    time.sleep(1)
    print("It took you a couple of hours to get there.")
    time.sleep(1)
    print("When there you explained your situation to the lady at the counter.")
    time.sleep(1)
    print("The lady checks and tells you that you can stay here for the night.")
    time.sleep(1)
    print("But tommorow you need to go to a different asylum center.")
    time.sleep(1)
    print("So you take you rest here tonight.")
    time.sleep(1)
    print("The next day you are of to the asylum center she mentioned.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    neatria_epilogue()

def refugee_camp():
    print("You find out that most people in this camp are stuck here because the will not be let through to other countries.")
    time.sleep(1)
    print("And even some people in the camps were send back to there own country.")
    time.sleep(1)
    print("There is no way to contact your friends or family.")
    time.sleep(1)
    print("The conditions in this camp is really bad and sometimes big fights break out over almost nothing.")
    time.sleep(1)
    print("Some people try to climb over the fence or try to find other ways out.")
    time.sleep(1)
    print("And some of them wait here untill they can leave.")
    time.sleep(1)
    print("This feels so horrible.")
    time.sleep(1)
    print("You will try to make the best of it as you can at this place.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    refugee_epilogue()

def jupinia_shelter():
    print("The truck driver calls his friends to help.")
    time.sleep(1)
    print("After he is done with the call he says that you need to wait here and they will pick you up.")
    time.sleep(1)
    print("So you do what he told you.")
    time.sleep(1)
    print("You wait there for a while and see a police car driving to you.")
    time.sleep(1)
    print("Cop: He you there.")
    time.sleep(1)
    print("You look at the cop and ask if he means you.")
    time.sleep(1)
    print("Cop: Yeah you I heard from my comrade that you needed help and want to settle in this beautiful country.")
    time.sleep(1)
    print("You say you indeed are looking for shelter and possible want to temporally live here.")
    time.sleep(1)
    print("Cop: Thats wonderfull comrade.")
    time.sleep(1)
    print("Cop: Come with us and you will see how wonderfull this country is.")
    time.sleep(1)
    print("You agree to go with the cop.")
    time.sleep(1)
    print("The cop brings you to asylum center of country.")
    time.sleep(1)
    print("And tells you everything will be fine.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")
    print(" ")
    jupinia_epilogue()

#------------------------------------------------------------------------------------------------------------------------------------------------------------------
# part 4 epilogue
def kolit_epilogue():
    print("So you go to bed.")
    time.sleep(1)
    print("The next day the man from the car comes by and tells you were you will go to work and what needs to be done.")
    time.sleep(1)
    print("For the next couple of months you help them and you slowly built up your reputation.")
    time.sleep(1)
    print("You finnaly got a bigger and nicer place to stay.")
    time.sleep(1)
    print("Its hard work to stay here but you think its worth it.")
    time.sleep(1)
    print("They allowed you to contact your family and friends.")
    time.sleep(1)
    print("They are still in the shitty country that you left.")
    time.sleep(1)
    print("You can see them soon if you work hard for the city.")
    time.sleep(1)
    print("You wish you didn't need to work so hard but you're at least happy that you are safe.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    print("GOOD END KOLIT")
    time.sleep(1)
    print(" ")
    print("ENDING KOLIT")
    print("Congratz you survived")
    time.sleep(1)
    print("I hope you had fun with your adventure.")
    time.sleep(1)
    print("credits:")
    time.sleep(1)
    print("Programmed by Michelle Simone Frankfort")
    print(67 * "-")
    print(" ")
    print("Special thanks to you the player for playing this.")
    time.sleep(1)
    print("Hope to see you again at my next projects.")
    console.check_answer("Plz press enter to continue.")
    play_again()

def neatria_epilogue():
    print("At the other ayslum center you learn that you need to proof that you're really in danger in your own country.")
    time.sleep(1)
    print("So you shown them documents and some other stuff that you have on your e-mail.")
    time.sleep(1)
    print("After sorting that out.")
    time.sleep(1)
    print("You find that you need to do a intergration course to be officially allowed to be a residence of this country.")
    time.sleep(1)
    print("So you do the intergration course.")
    time.sleep(1)
    print("You find it hard to learn a other language.")
    time.sleep(1)
    print("But you still do it because you want to have a place you can live freely and without fear.")
    time.sleep(1)
    print("You also had some contact with your family and its maybe possible that with a specail program that they can come to Neatria.")
    time.sleep(1)
    print("You're incredibly happy with your life.")
    time.sleep(1)
    print("You're so happy that you ended up at such an wonderfull place.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    print("GOOD END NEATRIA")
    time.sleep(1)
    print(" ")
    print("ENDING NEATRIA")
    print("Congratz you survived")
    time.sleep(1)
    print("I hope you had fun with your adventure.")
    time.sleep(1)
    print("credits:")
    time.sleep(1)
    print("Programmed by Michelle Simone Frankfort")
    print(67 * "-")
    print(" ")
    print("Special thanks to you the player for playing this.")
    time.sleep(1)
    print("Hope to see you again at my next projects.")
    console.check_answer("Plz press enter to continue.")
    play_again()

def refugee_epilogue():
    print("The next couple of months are rough and hard to get trough.")
    time.sleep(1)
    print("You feel like this was not the right choose.")
    time.sleep(1)
    print("You help a lot of people in the camp because there is not much else for you to do here.")
    time.sleep(1)
    print("You hope you can soon can go to a better place.")
    time.sleep(1)
    print(" ")
    print("ENDING REFUGEE CAMP")
    print("Congratz you survived")
    time.sleep(1)
    print("I hope you had fun with your adventure.")
    time.sleep(1)
    print("credits:")
    time.sleep(1)
    print("Programmed by Michelle Simone Frankfort")
    print(67 * "-")
    print(" ")
    print("Special thanks to you the player for playing this.")
    time.sleep(1)
    print("Hope to see you again at my next projects.")
    console.check_answer("Plz press enter to continue.")
    play_again()

def jupinia_epilogue():
    print("The people at the ayslum help you out with slowly getting everything on track to get your residence visa.")
    time.sleep(1)
    print("You find the costums in the country wierd and unusual but you're slowly starting to get the hang of it.")
    time.sleep(1)
    print("Will being there you started your integration and will soon get the integrations these so that you can get the residence visa.")
    time.sleep(1)
    print("Jupinia is lovely country but you still miss your family every day.")
    time.sleep(1)
    print("There is no way to contact them.")
    time.sleep(1)
    print("But you're at least relieved that you are safe.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    print("GOOD END JUPINIA")
    time.sleep(1)
    print(" ")
    print("ENDING JUPINIA")
    print("Congratz you survived")
    time.sleep(1)
    print("I hope you had fun with your adventure.")
    time.sleep(1)
    print("credits:")
    time.sleep(1)
    print("Programmed by Michelle Simone Frankfort")
    print(67 * "-")
    print(" ")
    print("Special thanks to you the player for playing this.")
    time.sleep(1)
    print("Hope to see you again at my next projects.")
    console.check_answer("Plz press enter to continue.")
    play_again()

def play_again():
    print(" ")
    print(67 * "-")
    print(" ")
    print("Do you want to restart the adventure, go back to the menu or quit the game?")
    time.sleep(1)
    print("1. Restart")
    time.sleep(1)
    print("2. Quit")
    time.sleep(1)
    print("3. Menu")
    time.sleep(1)
    again = console.check_answer("Restart, quit or menu: ", ["1", "yes", "y", "restart", "2", "no", "n", "quit", "3", "menu", "m"]).lower()
    if again == ("1") or again == ("yes") or again == ("y") or again == ("restart"):
        print("Okay")
        print("Good luck on your next run")
        adventure()
    elif again == ("2") or again == ("no") or again == ("n") or again == ("quit"):
        quit()
    elif again == ("3") or again == ("menu") or again == ("m"):
        print("Lets go back to the menu")
        time.sleep(1)
        print(" ")
        print(67 * "-")
        print(" ")

# starts the game and menu
while start == True:
    Menu.print_menu()
    menu = console.check_answer("What do you want to do?", ["1", "intro", "start", "2", "skip", "quit", "3", "help", "4"])
    print(" ")
    if menu == ("1") or menu == ("intro") or menu == ("start"):
        intro()
    elif menu == ("2") or menu == ("skip"):
        adventure()
    elif menu == ("help") or menu == ("3"):
        help()
    elif menu == ("quit") or menu == ("4"):
        quit()