import sys
import time
import random
from menu import Menu
from game_engine import Console, Player

console = Console()
player = Player()
start = True
basement_suprise = ["demon", "open", "closed", "bear"]
sus_building = ["enemy_trap", "human_traffic", "smuggler"]
boat_stuff = ["tip over", "fight", "safe"]
truck_survive = ["no", "yes"]
# I know I don't need so many varibles but still I don't care
go_in = " "
choice = " "
name = " "
start_sim = " "
enter = " "
trust = " "
enter_tower_1 = " "
retry_input = " "
jump_1 = " "
wake_up = " "
escape = " "
bye = 0

# Function to exit the game
def quit():
    print("Okay bye")
    exit(0)

# put the intro here
def intro():
    print("You were invited by your friend to test his newest simulator.")
    time.sleep(1)
    print("He wanted to see how you would react on his invention.")
    time.sleep(1)
    print("Because he wanted to see how people would react on fleeing there own country.")
    time.sleep(1)
    print("And to discover how it is to trade a place you are familiar with for something new.")
    time.sleep(1)
    print("Far away from your friends and family.")
    time.sleep(1)
    print("So he created this simulator called escape simulator.")
    time.sleep(1)
    print("He told you the simulation will take place in a land called Narlilia.")
    time.sleep(1)
    print("The country is in constant war with the civilians.")
    time.sleep(1)
    print("The war is getting so out of hand that the civilians are starting to attack you for being befriend with the leader of the resistance.")
    time.sleep(1)
    print("You don't see a other way out anymore than to escape from the country.")
    time.sleep(1)
    print("The country you love and grow up in.")
    time.sleep(1)
    print("Will you manage to escape out of this country or fail horribly.")
    time.sleep(1)
    console.check_answer("Plz press enter to continue.")

    adventure()

def help():
    print(" ")
    print(67 * "-")
    print(" ")
    console.check_answer("Plz press enter to continue.")

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Start part 0
# Start adventure
def adventure():
    print("@: Is anybody there???: ")
    console.check_answer("Plz press enter to continue.")
    time.sleep(1)
    print("@: WHAAAAAA!!!!")
    time.sleep(1)
    print("@: Oh sorry. I didn't expect that you where here already.")
    time.sleep(1)
    player.set_name(console.check_answer("So what is our name user?"))
    print("@: Oh hi " + player.get_name(name) + ". It's nice to meet you.")
    time.sleep(1)
    print("@: I'm escape simulator.")
    time.sleep(1)
    print("@: I'm here to teach you how it is to escape the country you currently live in")
    time.sleep(1)
    print("@: So shall we start the simulator?")
    time.sleep(1)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    print(" ")
    print(67 * "-")
    print(" ")
    run()

def run():
    start_sim = console.check_answer("Will you start the sim?: ", ["1", "yes", "y", "2", "no", "n"]).lower()
    if start_sim == ("1") or start_sim == ("yes") or start_sim == ("y"):
        print("Nyaaa")
        Sim_start()
    elif start_sim == ("2") or start_sim == ("no") or start_sim == ("n"):
        print("@: Uhmmm...")
        time.sleep(1)
        print("@: Are you sure?")
        time.sleep(0.5)
        print("1. Yes")
        time.sleep(0.5)
        print("2. No")
        time.sleep(0.5)
        print(67 * "-")
        print(" ")
        run2()

def run2():
    sure = console.check_answer("Are you sure?: ", ["1", "yes", "y", "2", "no", "n"]).lower()
    if sure == ("1") or sure == ("yes") or sure == ("y"):
        print("@: Ohhh bye then")
        time.sleep(0.5)
        print("You left the simulator alone without going on the adventure.")
        time.sleep(0.5)
        print("You never know what would have happened")
        time.sleep(0.5)
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        print(" ")
        time.sleep(1)
        print("ENDING 1")
        print("Nope not going to do this")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif sure == ("2") or sure == ("no") or sure == ("n"):
        retry()

def retry():
    print(" ")
    print(67 * "-")
    print(" ")
    time.sleep(1)
    print("So do you want to start the simulator?")
    time.sleep(0.5)
    print("1. yes")
    time.sleep(0.5)
    print("2. no")
    time.sleep(0.5)
    retry_input = console.check_answer("start simulator?: ", ["1", "2", "yes", "y", "no", "n"]).lower()
    if retry_input == ("1") or retry_input == ("yes") or retry_input == ("y"):
        print(" ")
        Sim_start()
    elif retry_input == ("2") or retry_input == ("no") or retry_input == ("n"):
        print("@: ARE")
        time.sleep(0.5)
        print("@: YOU")
        time.sleep(0.3)
        print("@: KIDDING")
        time.sleep(0.2)
        print("@: ME!!!!!!!")
        time.sleep(3)
        print("Good job you made the program so pissed that it blow it self up.")
        time.sleep(1)
        print("Now you can't enter the simulator anymore.")
        time.sleep(1)
        print("GG player")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING 2")
        print("BYE BYE SIMULATOR")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()

# -------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# End part 0
# Start part 1
def Sim_start():
    print("You hear a dull beep noise.")
    print("It sounds like your alarm is going of.")
    print("So what will you do?")
    print("1. Wake up.")
    print("2. Go back to sleep.")
    print("3. Throw your alarm out of the window.")
    wake_up = console.check_answer("while you go back to sleep or wake up: ", ["1", "wake up", "2" , "sleep", "3", "throw"]).lower()
    if wake_up == "1" or wake_up == "wake up":
        print("You wake up and turn of your alarm.")
        print("You look at the time and you see that its 10.00 am.")
        print("You get up out of bed and get yourself ready.")
        print("Outside you hear the occasional screaming of people and gunshots being fired in the far distance.")
        print("You are kind of getting sick of this.")
        print("You go down stairs to get some breakfast.")
        print("When you got down stairs you see some shady people sitting in your living room.")
        shady_people()
    elif wake_up == "2" or wake_up == "sleep":
        print("zzzzzz")
        print("zzzzzzzzzzzzzzz......")
        print("You hear suddenly a loud scream.")
        print("???: He you lazy peace of shit wake the fuck up!!!!")
        print("That immediately wakes you up.")
        print("You look around and then you see your best friend standing by your bed trying to wake up.")
        print("Her name is Monika and she is the leader of the local resistance group.")
        print("Monika: Ah you finnally awake.")
        print("Monika: That took you long enough.")
        print("You ask what is going on and why she woke you up.")
        print("Monika: There is no time to explain.")
        print("Monika: We need to get out of here right the fuck now.")
        print("You do what Monika tells you.")
        print("You quickly put on some clothes and leave your house through the back door.")
        quick_escape()
    elif wake_up == "3" or wake_up == "throw":
        print("You grab your alarm and throw it out of the window.")
        print("The alarm hits the head of a unexpect civilian.")
        print("People though it was a bomb you throw out so they throw a grenade back to you.")
        print("*booooooooommmmmm*")
        print("You got hit by the explosion and died instantly.")
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING 3")
        print("Unexpected event")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    
def shady_people():
    print("You look again and see its your best friend Monika and some friends of her.")
    print("Monika is the leader of the resitance in your neighborhood.")
    print("You start asking what they are doing here.")
    print("Monika: We are here to warn you that there are some people after you.")
    print("Monika: And its is the best that you get out of here.")
    print("Monika: The country is not safe anymore for you.")
    print("Monika: The found out that you're befriend with me.")
    print("You ask her what you need to do and if your family is safe.")
    print("Monika: We have prepared for you a escape route you can take to get out of here.")
    print("Monika: And don't worry about your family they are safe.")
    print("Monika: I know some people that can help you leave the country.")
    print("Monika's phone goes of.")
    print("Monika picks up the phone and start talking to the person on the phone.")
    print("After a few minutes of Monika being on the phone.")
    print("Monika look at you and signs that you need to leave")
    print("You know something bad is going to happen.")
    print("How will you leave or will you hide?")
    print("1. Front door.")
    print("2. Back door.")
    print("3. Hide in the basement")
    escape = console.check_answer("what do you do?: ", ["1", "2", "3", "front", "back", "hide"]).lower()
    if escape == "1" or escape == "front":
        print("You quickly make your way towards the front door.")
        print("You look through the window see if its safe to run.")
        print("On that moment some throws a smoke grenade on the street.")
        print("This is my change to escape.")
        print("You quickly run outside and run a few streets over.")
        print("You see a man stand there with a van.")
        print("He seem to recognize you")
        print("Van man: Hey " + player.get_name(name) + ". How is it going?")
        print("When you get closer to him you start to recognize him.")
        print("Its a your good pall Pablo.")
        print("You tell him what is going on.")
        print("Pablo: Awhhhh thats bad man.")
        print("Pablo: But I think I can help you.")
        print("Pablo: I know a few friends that do this for business.")
        print("Pablo: I can bring you in contact with them.")
        pablo_escape()
    elif escape == "2" or escape == "back":
        print("You go through the back door.")
        print("You see some friends from Monika waiting there for you at a van.")
        print("A guy walks up to you.")
        print("A guy: Hey, I heard you needed help getting out of the country, right?")
        print("You tell him that you indeed do and that you need to leave right now.")
        print("The guy node's and walks up to the van.")
        print("A guy: Here look everything we need to cross the borders all arranged by my boss.")
        print("You look in the van and see fake passports and some other stuff.")
        monika_escape()
    elif escape == "3" or escape == "hide":
        print("You quickly make your way to your basement door.")
        print("You open you basement door and go down into your basement.")
        print("You pick up a heavy piece of wood you found on the ground and try to block the door with it.")
        print("You wait a while in the basement.")
        basement()

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# RNG route
def basement():
    choice = random.choice(basement_suprise)
    if choice == "bear":
        print("You feel like someone is breathing in your neck.")
        print("You slowly turn around in the dark basement to check what it is.")
        print("You put your hands forward to feel what it is.")
        print("It feels really fluffy and fur like.")
        print("Wait a second you think to yourself.")
        print("It would have impossible that that bear you locked up here a few days weeks ago is still right.")
        print("Will your are thinking about it the bear is getting ready to murder you")
        print("*slash* And there you go.")
        print("Killed by a bear.")
        print("R.I.P. " + player.get_name(name) + ".")
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING BEAR")
        print("schrödinger bear")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "demon":
        print("You are alone down in the basement.")
        print("You suddenly hear a voice coming from the dark corner of the room.")
        print("Co...me.... wi....th.. u...s....")
        print("You were pretty sure that there is nothing else down here..... RIGHT????")
        print("You feel chill flowing down your spine.")
        print("You know there is something down here. There has to be right......")
        print("You starting to panic and don't know what to do.")
        print("The panic is so overwhelming that you feel like that you don't want to be here anymore.")
        print("You lose consciousness.")
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING 666")
        print("Demonic take over")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "open":
        print("After hiding in the basement for a while you hear some people entering your house.")
        print("Angery man: Hey " + player.get_name(name) + "we know your in here.")
        print("You hear them going through your house.")
        print("You hope the are unable to find you.")
        print("You suddenly hear them kicking against the basement door")
        print("You hope the door can hold it.")
        print("Then you hear *bam* the door flies downwards right in your face.")
        print("The door knocks you unconscious.")
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING DOOR")
        print("Knock knock who is there?")
        print("The door")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "closed":
        print("After hiding in the basement for a while you hear some people entering your house.")
        print("Angery man: Hey " + player.get_name(name) + "we know your in here.")
        print("You hear them going through your house.")
        print("You hope the are unable to find you.")
        print("You suddenly hear them kicking against the basement door")
        print("You hope the door can hold it.")
        print("You hear this guy trying really hard to open up the door but the door won't budge.")
        print("Then you hear someone yell.")
        print("Angery man: Guys he is nowhere to be found lets move out.")
        print("You hear everyone that is upstairs leave.")
        print("You survived this stressfull ordeal.")
        escaped_basement()

def escaped_basement():
    print("You slowly make your way to the basement door.")
    print("You put your ear up to the door to be sure that everyone left.")
    print("You don't hear anything.")
    print("You slowly open the door and hope that there is no one left.")
    print("When you look around you don't see a single person in the building left.")
    print("You go through the back door and run a trough a couple of streets.")
    print("You see there a sign above a build saying 'way out of the country'.")
    print("It look really shady but you think to yourself what other choose do I have left.")
    print("Do you go in or search for a other way out?")
    print("1. Go in.")
    print("2. Search for a other way.")
    go_in = console.check_answer("What do you do?", ["1", "2", "go in", "search"]).lower()
    if go_in == "1" or go_in == "go in":
        print("You go into the suspicious building.")
        suspicious_building()
    elif go_in == "2" or go_in == "search":
        print("You decide not to go into the building.")
        print("You continue your run till you come across a familiar face.")
        print("Nick: Howdy man.")
        print("Its your friend Nick")
        print("Nick is a master in getting people out of the country maybe he can help.")
        print("So you ask Nick if he can get you out of this country because some bad people are looking for you.")
        print("Nick: Yeah ofcourse, man.")
        print("Nick: I can get you out right now if you want.")
        print("Nick: You know its free because your my best pal.")
        print("Nick hands you some stuff and then walks to his car.")
        print("Nick: He come man lets go.")
        print("You go into Nick's car.")
        print("You think to yourself what do I have to lose.")
        escape_nick()

def suspicious_building():
    choice = random.choice(sus_building)
    if choice == "enemy_trap":
        print("You just walk into the trap of the poeple that are looking for you.")
        print("They take you hostage.")
        print("They want to know where Monika is.")
        print("Obviously you don't know where she is.")
        print("Now your stuck here with the people that want you as hostage and then dead.")
        print(67 * "-")
        print(" ")
        print("GAME OVER")
        time.sleep(1)
        print(" ")
        print("ENDING TRAP")
        print("Its a trap")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
    elif choice == "human_traffic":
        print("You see a man sitting behind a table.")
        print("Man: Hello stranger, are you here for help to get out of the country?")
        print("You find the man pretty suspicious but you feel like you have no other choose.")
        print("You say to him that you indeed need to get out of the country.")
        print("Man: Ah okay. I will help you get out of here.")
        print("The man gives you a form.")
        print("You read trough the form.")
        print("In the form stands that you will sell them your property and give them a amount of money.")
        print("You feel like this is wrong")
        print("But it feels like you have no other option.")
        print("So you sign the form and give it back to the man.")
        print("The man smile's and gives you a piece of paper")
        print("Man: Be on time.")
        print("On the paper stands a location and time.")
        escape_traffic()
    elif choice == "smuggler":
        print("You enter a huge warehouse.")
        print("Man: Ah welcome welcome.")
        print("You get greeted by a strange man.")
        print("Man: So you are here to get out of the country yeah right.")
        print("You tell him that you indeed need to get out of the country.")
        print("Man: Ofcourse ofcourse.")
        print("Man: I have a wonderfull way yeah.")
        print("You ask him how he will get you out.")
        print("Man: I will put you hidden in this trucks.")
        print("The man points to the trucks in the warehouse.")
        print("This feels like a stupid idea.")
        print("But it feels like you don't have an other choose.")
        escape_truck()

#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# quick escape route
def quick_escape():
    print("When going through the backdoor you see a wierd guy standing there in all black.")
    print("Man in black: Did you ever had a dream" + player.get_name(name) + "that you seemed so sure it was real?")
    print("You think what the hell is this man talking about and why does he know my name.")
    print("You ask him what the hell he is talking about.")
    print("Man in black: Oh you don't know who I am" + player.get_name(name) + ".")
    print("Man in black: Its me simon.")
    print("Simon: The person that let you play this simulator.")
    print("Simon: It looks like you got stuck in the simulator and I can't get you out again.")
    print("You get what he is saying.")
    print("You indeed entered the simulator in his place.")
    print("You try to exucte the quit command but the sytem give a error.")
    print("Simon: See the system won't let you out anymore.")
    print("Simon: You have to follow me to be able to escape the simulator.")
    print("You suddenly get a message from the system.")
    print("@: Don't trust him he is a glitch.")
    print("Simon: Come with me.")
    print("What will you do.")
    print("1. Go with Simon")
    print("2. Trust system")
    trust = console.check_answer("Simon: Do you trust me?").lower()
    if trust == "1" or trust == "yes":
        print("You trust Simon.")
        print("You follow Simon trough the streets.")
        print("You end up at a really tall building.")
        print("Simon: Lets go in.")
        print("@: Don't go in.")
        print("@: Plz I can't help you if you go.")
        enter_tower()
    elif trust == "2" or trust == "no":
        print("You trust the sytem.")
        print("@: Run away from him.")
        print("@: He is dangerous.")
        print("@: Follow my signs")
        print("Will running you see Simon chasing you")
        print("Simon is slowly changing in a wierd like demon creature.")
        print("Simon: Please come back.")
        print("Simon: The system is trying to trap you.")
        print("You keep following the systems arrows till you get at a cliff.")
        jump()

def enter_tower():
    print("Do you want to enter the tower?")
    print("1. Ent3r tower")
    print("2. Enter tow3r")
    print("3. Enter t0wer")
    print("4. Don't 3nter t0wer")
    print("%, En13r 10w3r")
    enter_tower_1 = console.check_answer("DO YOU ENTER THE TOWER?", ["1", "2", "3", "4", "%", "5", "enter"]).lower()
    if enter_tower_1 == "1" or enter_tower_1 == "2" or enter_tower_1 == "3" or enter_tower_1 == "5" or enter_tower_1 == "enter":
        print("You walk into the tower")
        print("Upon touching the door of the tower you feel like something is trying to corrupt you.")
        print("S!M0N: Whahahaha, it looks like my plan worked.")
        print("You ask S!M0N what the hell is going on here.")
        print("While you ask this you feel immense amount of pain flowing trough you.")
        print("@: Nooooooo, you walked right into the glitch trap.")
        print("S!M0N: Shut up system this user is mine now.")
        print("Suddenly you feel a rush of information going trough you.")
        print("After that you feel like your conscious is slowly fading away.")
        print("FATAL ERROR")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 4")
        print("Fatal take over")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif enter_tower_1 == "4":
        print("You decide to listen to the system.")
        print("You turn around and make a run for it.")
        print("You feel like Simon has been taken over by something very evil.")
        print("@: Follow my signs")
        print("You follow systems signs.")
        print("Until you end up at the end of the cliff.")
        jump()

def jump():
    print("@: Please jump down.")
    print("@: Trust me" + player.get_name(name) + ".")
    print("Do you jump?")
    print("1. Yes")
    print("2. No")
    jump_1 = console.check_answer("Will you jump?", ["1", "2", "yes", "no", "y", "n"]).lower()
    if jump_1 == "1" or jump_1 == "yes" or jump_1 == "y":
        print("You jump down off the cliff.")
        print("Will falling you feel lik everthing around you is disappearing.")
        print("Until you see a bright light.")
        print("Suddenly you wake up in the real world.")
        print("You ask escape simulator what was going on.")
        print("@: Oh sorry that was glitched AI.")
        print("@: He was someone Simon put into the game to let him learn from human actions.")
        print("@: But what happened in stead was that AI longed to be human.")
        print("@: So he waited for a unexpected user that he could manipulate.")
        print("@: So when he saw you he tought he could take his opportunity to strike.")
        print("@: But as you can see he failed.")
        print("@: So congratz user you succeeded at escaping.")
        print("@: This is the end.")
        print("@: I know this wasn't the end you were hoping for but still.")
        print("@: I will now wish you farewell user and good luck with everything in live.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("CONGRATZ ON ESCAPING THE PROGRAM!")
        time.sleep(1)
        print(" ")
        print("Ending 6")
        print("Getting out of here")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif jump_1 == "2" or jump_1 == "no" or jump_1 == "n":
        print("You decide not to jump.")
        print("Simon jumps on you and devours you.")
        print("FATAL ERROR")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 5")
        print("Didn't jump")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()

#------------------------------------------------------------------------------------------------------------------------------------------------------------------
# part 2 escape out of the country
def pablo_escape():
    print("Pablo takes out his phone and starts a phone call.")
    print("After a while Pablo comes back to you")
    print("Pablo: The are coming this way.")
    print("So you wait there with Pablo for his friends.")
    print("Then Pablo's friends arive.")
    print("Man 1: So who is the person that we need to help.")
    print("Pablo: My friend is here.")
    print("Then Pablo points at you.")
    print("Man 1: Okay come with us.")
    print("You start to follow the Man.")
    print("You then get to a car.")
    print("When you are at the car the man put a bag suddenly over your head.")
    print("You want to scream but you suddenly get knocked out.")
    print("After a while you wake up.")
    print("You are stuck in a cage")
    print("When you look around you you see more people that are stuck in cage's.")
    print("You feel like you fall in a trap.")
    time.sleep(1)
    print(67 * "-")
    print(" ")
    print("SLAVE OR WORSE")
    time.sleep(1)
    print(" ")
    print("ENDING 8")
    print("Became a slave or something.")
    time.sleep(1)
    console.check_answer("Plz press enter to continue.")
    play_again()

def escape_traffic():
    print("You go to the specified location on the paper.")
    print("When you arive there you a bunch of people getting loaded on a small boat.")
    print("You walk up to the man and ask if you are at the right spot.")
    print("The man say you're and that you need to get a board of the boat.")
    print("You do what the tell you and get onto the boat.")
    print("Once everyone was a board of the boat you guys took of.")
    print("This boat will hopefully take you guys over the ocean out of the country.")
    print("The trip is taking a while now.")
    print("You guys are now drifting on the occean slowly trying to go to your destination.")
    print("Everyone on the boat looks terrified and hope they can make it on shore.")
    print("You even hear a baby cry on boat.")
    print("You really hope al of you can make it safely on shore.")
    boat_trip()

def boat_trip():
    choice = random.choice(boat_stuff)
    if choice == "tip over":
        print("After a while its starts to strom.")
        print("The ocean is getting pretty wild and you feel the boat is going to tip over.")
        print("And then it happens a huge wave hits the boat.")
        print("Everybody starts to scream for there live.")
        print("The boat tips over.")
        print("After that you get pushed down by the waves.")
        print("You try to swim up but its futile.")
        print("YOU DIED")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 6")
        print("The drowned")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "fight":
        print("There suddenly breaks out a fight on the boat.")
        print("People are pissed at each other.")
        print("Because of the fighting people are starting to fall of.")
        print("And then suddenly you get a person shoved in your face.")
        print("You loss your balance and fall of the boat.")
        print("You start to drift in the ice cold water.")
        print("After a while you lose your concussions")
        print("YOU DIED")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 7")
        print("Pushed in sea.")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "safe":
        print("After a while you start to see land.")
        print("Everybody is happy but still really scared.")
        print("Eventually you guys hit land.")
        print("At land are some people that see you get at shore and want to help you.")
        print("After that you guys get brought to a camp.")
        print("At the camp you find out this is a refugee camp.")
        refugee_camp()

def monika_escape():
    print("A guy: Get in the van so that we can leave.")
    print("You do as you were told and enter the van.")
    print("Will being in the van you're told to be silence during the trip.")
    print("Then you hear the enigne of the van starting.")
    print("So the trip started.")
    print("You are there in the truck with a few other people.")
    print("You are going on a long trip trough country's to try to get to a safe country.")
    print("Its was a long trip.")
    print("By sitting hours on end with almost no breaks and almost no food.")
    print("The van made a couple of stops but we may not come out of the van")
    print("Sometimes the people of the customs would look into our truck and check our pasports.")
    print("After checking them the let us go.")
    print("After a while we finnaly stopped and the doors openend.")
    print("A guy: You may come out now.")
    print("A guy: Please follow me.")
    print("You follow the guy into a building that is tottally boarded of.")
    print("A guy: We will stay here for the night.")
    print("A guy: You guys may not go outside.")
    print("After he sayed that he went outside to smoke.")
    the_building()

def the_building():
    print("After the guy left you started to look around.")
    print("You see that there are two other guys also sitting in this building with you.")
    print("You try to start with them a conversation with them.")
    print("They say something along the lines of I'm tired please go to bed.")
    print("You don't have a good feeling about this place.")
    print("But you feel way to exhausted to do anything right now.")
    print("So you decide to sleep here tonight.")
    print("The next morning you got woken up by the guy that brought you here.")
    print("A guy: Lets go back to the van its going to be a long trip.")
    print("So you guys decide to go back into that afwull van.")
    print("You are again hours on end with no breaks in the van.")
    print("Till the van stops.")
    print("The doors opened up.")
    print("A guy: You may come out now.")
    print("You are in a luscious city.")
    print("After exiting the van the guy say that he needs to do something so you guys need to wait here.")
    print("You're super exhausted and don't feel like you want to travel anymore in that van.")
    print("You see some people walking by and want to ask them where you are in your best english.")
    print("They tell you that you're in the city Amsteria.")
    print("Amsteria is the main capital of the country Neatria.")
    shelter_Neatria()

def escape_truck():
    print("You start to follow the instructions of the man and you went into the hidden compartment.")
    print("The hidden compartment is not so big.")
    print("But it feels like you have no other choose.")
    print("So you wait in this compartment.")
    print("Then start the truck and starts your journey.")
    truck_trip()

def truck_trip():
    choice = random.choice(truck_survive)
    if choice == "no":
        print("The trip goes on for a while.")
        print("After a while you feel like you're getting sleepy.")
        time.sleep(1)
        print(67 * "-")
        print(" ")
        print("DEATH")
        time.sleep(1)
        print(" ")
        print("ENDING 9")
        print("No oxygen")
        time.sleep(1)
        console.check_answer("Plz press enter to continue.")
        play_again()
    elif choice == "yes":
        print("The trip continue's for a while.")
        print("You just relax in the truck and wait till you arive at your destination.")
        print("After a while the truck stop.")
        print("The compartment door goes open.")
        print("The truck driver stands there.")
        print("Driver: We have arrived.")
        print("You get slowly out of the compartment.")
        print("While going out you see that the sun is burning in your eyes.")
        print("You start to put your elbow in front of your face.")
        print("Then when trying to get out this way you loose your balance.")
        print("Driver: He calm there budy.")
        print("The driver catches and helps you to regain your balance.")
        print("You ask the driver where you are.")
        print("Driver: We are in the wonderfull country of Jupinia.")
        print("You think by yourself were that is.")
        print("Driver: It lays pretty far away from Narlilia.")
        print("Driver: So don't worry they won't get you here.")
        print("You're pretty happy to hear those words from the driver.")
        print("You ask where you can go for to register your self as refugee.")
        print("Driver: Ah okay I will bring you in contact with my friends.")
        jupinia_shelter()

def escape_nick():
    print("Nick start to drive trough the country with no worries that his car would get hit.")
    print("Will bombs are going of around us Nick is loudly singing with the song on the radio.")
    print("This goes on for awhile.")
    print("Till suddenly the car breaks down.")
    print("Nick: Ah fuck.")
    print("Nick: That was my favourite car.")
    print("You ask Nick where you guys are.")
    print("Nick: We are now in Kolit the neighboring country of Narlilia.")
    print("You ask if Nick know someone that you can go to and if its safe here.")
    print("Nick: I know a few friends that can help you.")
    print("Nick start to call them.")
    print("After Nick is done with the phone call he says that his friend will pick us up.")
    print("And that they can get me a job in this country and a place to live.")
    print("You wait there with Nick for a while.")
    print("Then a car comes driving towards you guys.")
    print("The car stops near Nicks broken down car.")
    print("Men from car: Hey Nick how is it going.")
    print("Nick: Not so well.")
    print("Nick: My car broke down will I was helping my pal " + player.get_name(name) + " .")
    print("Men from car: Yeah boss already told me that.")
    print("Men from car: So get in and we will get them a nice temporary place and job.")
    print("You get into the car of the men.")
    shelter_kolit()

#-------------------------------------------------------------------------------------------------------------------------------------------------------------
# part 3 New country
def jupinia_shelter():
    print("Jupinia")

def shelter_Neatria():
    print("Neatria")

def refugee_camp():
    print("Camp")

def shelter_kolit():
    print(" ")

def play_again():
    print(" ")
    print(67 * "-")
    print(" ")
    print("Do you want to restart the adventure, go back to the menu or quit the game?")
    time.sleep(1)
    print("1. Restart")
    time.sleep(1)
    print("2. Quit")
    time.sleep(1)
    print("3. Menu")
    time.sleep(1)
    again = console.check_answer("Restart, quit or menu: ", ["1", "yes", "y", "restart", "2", "no", "n", "quit", "3", "menu", "m"]).lower()
    if again == ("1") or again == ("yes") or again == ("y") or again == ("restart"):
        print("Okay")
        print("Good luck on your next run")
        adventure()
    elif again == ("2") or again == ("no") or again == ("n") or again == ("quit"):
        quit()
    elif again == ("3") or again == ("menu") or again == ("m"):
        print("Lets go back to the menu")
        time.sleep(1)
        print(" ")
        print(67 * "-")
        print(" ")

# starts the game and menu
while start == True:
    Menu.print_menu()
    menu = console.check_answer("What do you want to do?", ["1", "intro", "start", "2", "skip", "quit", "3", "help", "4"])
    print(" ")
    if menu == ("1") or menu == ("intro") or menu == ("start"):
        intro()
    elif menu == ("2") or menu == ("skip"):
        adventure()
    elif menu == ("help") or menu == ("3"):
        help()
    elif menu == ("quit") or menu == ("4"):
        quit()